[package]
name = "daily3014/cryptography"
description = "Luau implementations of popular hashing/encryption algorithms"
version = "1.11.0"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/daily3014/rbx-cryptography"

realm = "shared"
license = "MIT"
authors = ["daily3014", "xoifail"]

include = ["src", "src/**", "default.project.json", "wally.toml"]
exclude = ["**"]
